### ISSUE TITLE
Nix package broken

### ISSUE THREAD

**Issue by klarkc** [jaspervdj/patat#123]
I was trying to using it with nix:

```bash
nix-shell -p haskellPackages.patat

error: Package ‘patat-0.8.7.0’ in /nix/store/qb1d20c0rvf718yf505wkzb4bjbzqyiw-nixpkgs/nixpkgs/pkgs/development/haskell-modules/hackage-packages.nix:213831 is marked as broken, refusing to evaluate.
```

Running nix-build on nixpkgs got me this:
<details>
  <summary>Log</summary>
  
```
@nix { "action": "setPhase", "phase": "setupCompilerEnvironmentPhase" }
setupCompilerEnvironmentPhase
Build with /nix/store/kg7g827612mcbjdvxf71spb24z2mx6n7-ghc-9.0.2.
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/pzgpgkkizrbx004v7cg7y6m4z2jgqhkb-patat-0.8.7.0.tar.gz
source root is patat-0.8.7.0
setting SOURCE_DATE_EPOCH to timestamp 1615574599 of file patat-0.8.7.0/CHANGELOG.md
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "compileBuildDriverPhase" }
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-patat-0.8.7.0.drv-0/tmp.usGaILy2Zk/setup-package.conf.d -j4 +RTS -A64M -RTS -threaded -rtsopts
[1 of 1] Compiling Main             ( Setup.hs, /tmp/nix-build-patat-0.8.7.0.drv-0/tmp.usGaILy2Zk/Main.o )
Linking Setup ...
compileBuildDriverPhase completed in 34 seconds
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
configureFlags: --verbose --prefix=/nix/store/pmbhcnpd53k6ffx2lf00vnjzhgis6chr-patat-0.8.7.0 --libdir=$prefix/lib/$compiler --libsubdir=$abi/$libname --docdir=/nix/store/ihjlffciyr6b7dhihrh7mxhs0npsjinj-patat-0.8.7.0-doc/share/doc/patat-0.8.7.0 --with-gcc=gcc --package-db=/tmp/nix-build-patat-0.8.7.0.drv-0/tmp.usGaILy2Zk/package.conf.d --ghc-options=-j4 +RTS -A64M -RTS --disable-split-objs --enable-library-profiling --profiling-detail=exported-functions --disable-profiling --enable-shared --disable-coverage --enable-static --disable-executable-dynamic --enable-tests --disable-benchmarks --enable-library-vanilla --disable-library-for-ghci --ghc-option=-split-sections --ghc-options=-haddock --extra-lib-dirs=/nix/store/h7cgpyjcm7y9mrx5nm0whzk81rql6bd3-ncurses-6.3-p20220507/lib --extra-lib-dirs=/nix/store/4d4zzb9a4fazq0qv7vvls561l9cxi0zc-libffi-3.4.2/lib --extra-lib-dirs=/nix/store/g935jx00gb1gzgam4kh8xk9524fqbrdc-gmp-with-cxx-6.2.1/lib
Using Parsec parser
Configuring patat-0.8.7.0...

Setup: Encountered missing or private dependencies:
QuickCheck >=2.8 && <2.14,
aeson >=0.9 && <1.5,
ansi-terminal >=0.6 && <0.11,
base64-bytestring >=1.0 && <1.1,
optparse-applicative >=0.12 && <0.16,
pandoc >=2.11 && <2.12,
skylighting >=0.10 && <0.11,
tasty >=1.2 && <1.3
```
  
</details>

Relates #65

**Comment by klarkc** [comment]
Workaround: Got a very old version working (v0.8.1.3)

```bash
NIXPKGS_ALLOW_BROKEN=1 nix-shell -p haskellPackages.patat -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/96ceff97da009d9605287e70cd20b04409ea30c6.tar.gz
```

[Source](https://github.com/jaspervdj/patat/issues/65#issuecomment-510725975)

**Comment by athas** [comment]
I think this can be more or less solved by releasing a new version of patat on Hackage.

**Comment by klarkc** [comment]
Update:

I've got a working v0.8.8.0 from [929e5c](https://github.com/NixOS/nixpkgs/archive/929e5cd46eea8ba8cee6c975412d88594ada462c.tar.gz)

master still broken though

**Comment by dalpd** [comment]
https://github.com/NixOS/nixpkgs/commit/d3ba95407deecec4e925f513d7c49eae65ff249e fixes the build on master.

**Comment by klarkc** [comment]
Confirmed, working on master ([NixOS/nixpkgs@3364b5](https://github.com/NixOS/nixpkgs/commit/3364b5)).
